# Generated by Django 2.2.1 on 2020-03-14 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20200315_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='acquisition_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
