# Generated by Django 2.2.1 on 2020-03-15 00:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20200315_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='acquisition_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 15, 0, 9, 38, 570280, tzinfo=utc)),
        ),
    ]
