# Generated by Django 2.2.1 on 2020-03-15 00:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20200315_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='acquisition_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
