# Generated by Django 2.2.1 on 2020-03-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_auto_20200321_0338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appreciate',
            old_name='value',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='appreciate',
            old_name='appreciation_value',
            new_name='months',
        ),
        migrations.RenameField(
            model_name='depreciate',
            old_name='value',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='depreciate',
            old_name='depreciation_value',
            new_name='months',
        ),
    ]
